[persistence.py]
  [test_data_persists_after_closing]
    expected: FAIL
