[request.py]
  [test_provide_response_auth_required[fetch\]]
    expected: FAIL
