[collector.py]
  [test_data_not_available_after_remove]
    expected: FAIL
