[exception_details.py]
  [test_exception_details[undefined-expected0\]]
    expected: FAIL

  [test_exception_details[null-expected1\]]
    expected: FAIL

  [test_exception_details['foobar'-expected2\]]
    expected: FAIL

  [test_exception_details['2'-expected3\]]
    expected: FAIL

  [test_exception_details[NaN-expected4\]]
    expected: FAIL

  [test_exception_details[-0-expected5\]]
    expected: FAIL

  [test_exception_details[Infinity-expected6\]]
    expected: FAIL

  [test_exception_details[-Infinity-expected7\]]
    expected: FAIL

  [test_exception_details[3-expected8\]]
    expected: FAIL

  [test_exception_details[1.4-expected9\]]
    expected: FAIL

  [test_exception_details[true-expected10\]]
    expected: FAIL

  [test_exception_details[false-expected11\]]
    expected: FAIL

  [test_exception_details[42n-expected12\]]
    expected: FAIL

  [test_exception_details[(Symbol('foo'))-expected13\]]
    expected: FAIL

  [test_exception_details[[1, 'foo', true, new RegExp(/foo/g), [1\]\]-expected14\]]
    expected: FAIL

  [test_exception_details[({'foo': {'bar': 'baz'}, 'qux': 'quux', 1: 'fred', '2': 'thud'})-expected15\]]
    expected: FAIL

  [test_exception_details[(()=>{})-expected16\]]
    expected: FAIL

  [test_exception_details[(function(){})-expected17\]]
    expected: FAIL

  [test_exception_details[(async ()=>{})-expected18\]]
    expected: FAIL

  [test_exception_details[(async function(){})-expected19\]]
    expected: FAIL

  [test_exception_details[(function*() { yield 'a'; })-expected20\]]
    expected: FAIL

  [test_exception_details[new RegExp(/foo/g)-expected21\]]
    expected: FAIL

  [test_exception_details[new Date(1654004849000)-expected22\]]
    expected: FAIL

  [test_exception_details[new Map([[1, 2\], ['foo', 'bar'\], [true, false\], ['baz', [1\]\]\])-expected23\]]
    expected: FAIL

  [test_exception_details[new Set([1, 'foo', true, [1\], new Map([[1,2\]\])\])-expected24\]]
    expected: FAIL

  [test_exception_details[new WeakMap()-expected25\]]
    expected: FAIL

  [test_exception_details[new WeakSet()-expected26\]]
    expected: FAIL

  [test_exception_details[new Error('SOME_ERROR_TEXT')-expected27\]]
    expected: FAIL

  [test_exception_details[[1, 2\][Symbol.iterator\]()-expected28\]]
    expected: FAIL

  [test_exception_details['mystring'[Symbol.iterator\]()-expected29\]]
    expected: FAIL

  [test_exception_details[(new Set([1,2\]))[Symbol.iterator\]()-expected30\]]
    expected: FAIL

  [test_exception_details[(new Map([[1,2\]\]))[Symbol.iterator\]()-expected31\]]
    expected: FAIL

  [test_exception_details[new Proxy({}, {})-expected32\]]
    expected: FAIL

  [test_exception_details[(function*() { yield 'a'; })()-expected33\]]
    expected: FAIL

  [test_exception_details[(async function*() { yield await Promise.resolve(1); })()-expected34\]]
    expected: FAIL

  [test_exception_details[Promise.resolve()-expected35\]]
    expected: FAIL

  [test_exception_details[new Int32Array()-expected36\]]
    expected: FAIL

  [test_exception_details[new ArrayBuffer()-expected37\]]
    expected: FAIL

  [test_exception_details[document.createElement('div')-expected38\]]
    expected: FAIL

  [test_exception_details[window-expected39\]]
    expected: FAIL

  [test_exception_details[new URL('https://example.com')-expected40\]]
    expected: FAIL

  [test_invalid_script]
    expected: FAIL

  [test_rejected_promise[True\]]
    expected: FAIL

  [test_rejected_promise[False\]]
    expected: FAIL
