[fetch_error.py]
  expected: TIMEOUT
